# Generated by Django 6.0.8 on 2026-09-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('account_archive_id', models.CharField(max_length=64)),
                ('character_archive_id', models.CharField(max_length=64)),
                ('to_instance', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'scaling ticket',
                'verbose_name_plural': 'scaling tickets',
            },
        ),
    ]
